# embed_ui.cmake — pack the frontend/dist UI files and the WebView2 loader
# DLL into the exe as hex C++ tables (pure CMake, no Python/compiler).
#   cmake -P embed_ui.cmake
#          -DDIST=<dir>                  frontend/dist
#          -DLOADER=<WebView2Loader.dll>
#          -DOUT_H=<out.h>
#          -DOUT_CPP=<out.cpp>
if(NOT DEFINED DIST OR NOT DEFINED LOADER OR NOT DEFINED OUT_H OR NOT DEFINED OUT_CPP)
  message(FATAL_ERROR "embed_ui.cmake needs DIST, LOADER, OUT_H, OUT_CPP")
endif()
if(NOT EXISTS "${DIST}" OR NOT EXISTS "${LOADER}")
  message(FATAL_ERROR "DIST or LOADER not found")
endif()

file(GLOB_RECURSE UIFILES "${DIST}/*")
list(SORT UIFILES)

# --- helpers: hex-encode a small file into chunked C string fragments ---
function(hexify PATH OUT_VAR)
  file(READ "${PATH}" HEXCONTENT HEX)
  string(LENGTH "${HEXCONTENT}" HEXLEN)
  set(PARTS "")
  set(OFF 0)
  set(CHUNKSIZE 59712)   # even, < MSVC 65535 literal limit
  while(OFF LESS HEXLEN)
    math(EXPR NEXT "${OFF} + ${CHUNKSIZE}")
    if(NEXT GREATER HEXLEN)
      set(NEXT ${HEXLEN})
    endif()
    math(EXPR CL "${NEXT} - ${OFF}")
    string(SUBSTRING "${HEXCONTENT}" ${OFF} ${CL} CHUNK)
    set(PARTS "${PARTS}\"${CHUNK}\"\n")
    set(OFF ${NEXT})
  endwhile()
  math(EXPR BYTELEN "${HEXLEN} / 2")
  set(${OUT_VAR} "${PARTS}" PARENT_SCOPE)
  set(${OUT_VAR}_LEN "${BYTELEN}" PARENT_SCOPE)
endfunction()

set(UILIST "")
set(UIENTRIES "")
set(UICOUNT 0)
foreach(F ${UIFILES})
  file(RELATIVE_PATH REL "${DIST}" "${F}")
  string(REPLACE "\\" "/" REL "${REL}")
  string(REPLACE "/" "_" SYM "${REL}")
  string(REPLACE "." "_" SYM "${SYM}")
  string(REPLACE "-" "_" SYM "${SYM}")
  hexify("${F}" HEX_${SYM})                       # sets HEX_<sym> and HEX_<sym>_LEN
  set(DECL "extern \"C\" const char kUi_${SYM}_hex[];\nextern \"C\" const std::size_t kUi_${SYM}_len;")
  set(DEF "const char kUi_${SYM}_hex[] = ${HEX_${SYM}};\nconst std::size_t kUi_${SYM}_len = ${HEX_${SYM}_LEN};")
  set(ROW "    {\"${REL}\", kUi_${SYM}_hex, kUi_${SYM}_len},")
  set(UILIST "${UILIST}\n${DECL}\n${DEF}")
  set(UIENTRIES "${UIENTRIES}\n${ROW}")
  math(EXPR UICOUNT "${UICOUNT} + 1")
endforeach()

hexify("${LOADER}" LOADERHEX)

file(WRITE "${OUT_H}" "// Generated by embed_ui.cmake — DO NOT EDIT.
#pragma once
#include <cstddef>
struct UiPackFile { const char *rel; const char *hex; std::size_t len; };
extern \"C\" const UiPackFile kUiPackTable[];
extern \"C\" const std::size_t kUiPackCount;
extern \"C\" const char kWebView2LoaderHex[];
extern \"C\" const std::size_t kWebView2LoaderLen;
")

file(WRITE "${OUT_CPP}" "// Generated by embed_ui.cmake — DO NOT EDIT.
#include <cstddef>
#include \"ui_embedded.h\"
${UILIST}
extern \"C\" const UiPackFile kUiPackTable[] = { ${UIENTRIES}
    {nullptr, nullptr, 0}
};
extern \"C\" const std::size_t kUiPackCount = ${UICOUNT};
extern \"C\" const char kWebView2LoaderHex[] =
${LOADERHEX};
extern \"C\" const std::size_t kWebView2LoaderLen = ${LOADERHEX_LEN};
")