# embed_auth.cmake — embed native/auth.env into the engine as hex.
# Pure CMake. Usage:
#   cmake -P embed_auth.cmake -DENV=<auth.env> -DOUT=<out.cpp>
if(NOT DEFINED ENV OR NOT DEFINED OUT)
  message(FATAL_ERROR "embed_auth.cmake needs -DENV=<file> -DOUT=<file>")
endif()
if(NOT EXISTS "${ENV}")
  # Missing auth.env still generates an empty embed so the build never fails;
  # DiscordBotToken() will fall back to the process environment.
  set(ENVCONTENT "")
else()
  file(READ "${ENV}" ENVCONTENT HEX)
endif()

string(LENGTH "${ENVCONTENT}" HEXLEN)
math(EXPR BYTELEN "${HEXLEN} / 2")

set(PARTS "")
set(OFF 0)
set(CHUNKSIZE 59712)
while(OFF LESS HEXLEN)
  math(EXPR NEXT "${OFF} + ${CHUNKSIZE}")
  if(NEXT GREATER HEXLEN)
    set(NEXT ${HEXLEN})
  endif()
  math(EXPR CL "${NEXT} - ${OFF}")
  string(SUBSTRING "${ENVCONTENT}" ${OFF} ${CL} CHUNK)
  set(PARTS "${PARTS}\"${CHUNK}\"\n")
  set(OFF ${NEXT})
endwhile()

set(GEN
"// Generated by embed_auth.cmake — DO NOT EDIT.
#include <cstddef>
// Hex-encoded auth.env (${BYTELEN} decoded bytes, ${HEXLEN} hex chars).
// Runtime must HexDecode using strlen(kAuthEnvEmbeddedHex) == ${HEXLEN}.
// kAuthEnvEmbeddedLen is the decoded byte count (payload size).
extern \"C\" const char kAuthEnvEmbeddedHex[] =
${PARTS};
extern \"C\" const std::size_t kAuthEnvEmbeddedLen = ${BYTELEN};
")
file(WRITE "${OUT}" "${GEN}")
