# embed_tweaks.cmake — embed shell/Optimizer/tweaks.json into the engine
# as hex. Pure CMake (no Python/compiler needed). Usage:
#   cmake -P embed_tweaks.cmake -DJSON=<src.json> -DOUT=<out.cpp>
if(NOT DEFINED JSON OR NOT DEFINED OUT)
  message(FATAL_ERROR "embed_tweaks.cmake needs -DJSON=<file> -DOUT=<file>")
endif()
if(NOT EXISTS "${JSON}")
  message(FATAL_ERROR "tweaks JSON not found: ${JSON}")
endif()

# file(READ ... HEX) hex-encodes the whole file; hex is 2*bytes chars.
file(READ "${JSON}" HEXCONTENT HEX)
string(LENGTH "${HEXCONTENT}" HEXLEN)
math(EXPR BYTELEN "${HEXLEN} / 2")

# Split into C-string literals under MSVC's 65535-byte literal limit.
# Chunks are even-sized so hex pairs never split.
set(PARTS "")
set(OFF 0)
set(CHUNKSIZE 59712)
while(OFF LESS HEXLEN)
  math(EXPR NEXT "${OFF} + ${CHUNKSIZE}")
  if(NEXT GREATER HEXLEN)
    set(NEXT ${HEXLEN})
  endif()
  math(EXPR CL "${NEXT} - ${OFF}")
  string(SUBSTRING "${HEXCONTENT}" ${OFF} ${CL} CHUNK)
  set(PARTS "${PARTS}\"${CHUNK}\"\n")
  set(OFF ${NEXT})
endwhile()

set(GEN
"// Generated by embed_tweaks.cmake — DO NOT EDIT.
#include <cstddef>
// Hex-encoded shell/Optimizer/tweaks.json (${BYTELEN} bytes).
// Decoded and parsed lazily by px::tweaks::Doc().
extern \"C\" const char kTweaksEmbeddedHex[] =
${PARTS};
extern \"C\" const std::size_t kTweaksEmbeddedLen = ${BYTELEN};
")
file(WRITE "${OUT}" "${GEN}")